### ISSUE TITLE
How do I pass a secrets information into a json body payload?

### ISSUE THREAD

**Issue by BobSilent** [tanhakabir/rest-book#105]
When trying to add the secrets into the body json i get an error message.
![image](https://user-images.githubusercontent.com/13506173/121016997-13264480-c79d-11eb-8c50-d51f4977898a.png)

tried:
```JSON
   "userPassword": $SECRETS.mainanaPwd,
   "userPassword": "$SECRETS.mainanaPwd",
```

**Comment by tanhakabir** [comment]
Currently I don't have full variable support, specifically I'm missing variables in the body which is working progress currently.
Mentioned in https://github.com/tanhakabir/rest-book/issues/75 so I'm closing this one for that issue.
