### ISSUE TITLE
Is it possible to set a default mime-type and keep it that way?

### ISSUE THREAD

**Issue by nat1craft** [tanhakabir/rest-book#106]
I see where I can switch mime-types of the response. However, I really want to always see a specific mime-type by default. (say JSON).   Can this be done already, and if not, would it be possible to add it?

Great plugin.

**Comment by tanhakabir** [comment]
Thanks! This is a vscode issue which was mentioned here: https://github.com/microsoft/vscode/issues/125876. I believe this should be a feature that already works on vscode where the output you choose last should be the output renderer.

I'm going to close this issue to carry on the conversation on that issue.
