### ISSUE TITLE
Error: Invalid URL given!

### ISSUE THREAD

**Issue by TanukiSharp** [tanhakabir/rest-book#110]
Hello,

First, this extension is truly an awesome idea!

I have a backend running locally, so on `http://` only, and when I run a request, I get `Error: Invalid URL given!` error and nothing more.

Here is the code:

```
POST http://localhost:3000/myendpoint
Content-Type: application/json

{
    "value": 1
}
```

The backend works fine, since calling it with `wget`, `curl` and VS Code `RESTClient` extension all work fine. Is it because `http://` is not supported ?

I run REST Book version 2.1.0 on VS Code 1.57.1 (below are VS Code details)
```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z (4 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

Thanks.

**Comment by tanhakabir** [comment]
Hey! hmm I can't seem to repro your issue. When I'm running a simple express server I see this:

![image](https://user-images.githubusercontent.com/12758612/122977773-c9745700-d363-11eb-8e63-c245ebad898a.png)


Is there anything else I'm missing? Would I be able to test against your backend?

**Comment by TanukiSharp** [comment]
I think the reason is because I'm not running an insider build.

Here https://github.com/tanhakabir/rest-book/blob/main/src/common/request.ts#L186 the `tokens` contains the whole code split on spaces, including line feeds, so it looks like this:

```js
[
    'POST',
    'http://localhost:3000/myendpoint',
    '',
    'Content-Type:',
    'application/json',
    etc...
]
```

I'll just wait for next VS Code release and retry.

**Comment by tanhakabir** [comment]
Hmm on that line when you log the tokens you see `[ 'Content-Type:', 'application/json' ]` in there? That's unexpected because that function is only splitting the first line of the request sho it should be just: `[ 'POST', 'http://localhost:3000/myendpoint' ]`

**Comment by TanukiSharp** [comment]
I opened file `<home>\.vscode\extensions\tanhakabir.rest-book-2.2.0\dist\extension-node.js` file and added a few logs.

https://github.com/tanhakabir/rest-book/blob/main/out/common/request.js#L12
`query` prints this:
![image](https://user-images.githubusercontent.com/4018313/123343132-1b97c100-d58c-11eb-8fbd-58e143f334cc.png)

https://github.com/tanhakabir/rest-book/blob/main/out/common/request.js#L112
`this.originalRequest` prints this (twice):
![image](https://user-images.githubusercontent.com/4018313/123343191-4124ca80-d58c-11eb-9e56-717f2055ba35.png)

https://github.com/tanhakabir/rest-book/blob/main/out/common/request.js#L120
`tokens` prints this:
![image](https://user-images.githubusercontent.com/4018313/123343235-58fc4e80-d58c-11eb-8926-511a269ff266.png)

I'm running on Windows 10.

I hope this helps.

**Comment by tanhakabir** [comment]
Thanks this is helpful! I'll take a look later today

**Comment by UndefinedOffset** [comment]
I just ran into this, in my case it seems to be an issue between Windows line ends (`\r\n`) and unix line ends `\n`. In my case VSCode is set to use unix line ends, on a Windows system. If I modify the json to have `\r\n` in place of the unix line ends in the json strings it works as expected. But the rest book editor is writing `\n` into the json strings.
