### ISSUE TITLE
Cannot include spaces in URL; %20 is re-encoded to %2520

### ISSUE THREAD

**Issue by jvanitallie** [tanhakabir/rest-book#113]
Trying to send OData filters in the URI and I need to include spaces.  The spaces are reporting as "Invalid URL" from within RestBook, and if I try to escape them myself with either `%20` or `+`, RestBook tries to encode that again for me.

![2021-07-05_15-22-39](https://user-images.githubusercontent.com/53232322/124511875-1d8c2c00-dda5-11eb-83ed-ce09d4b0897b.jpg)
![2021-07-05_15-23-06](https://user-images.githubusercontent.com/53232322/124511885-1fee8600-dda5-11eb-95ee-06c872975dee.jpg)
![2021-07-05_15-23-19](https://user-images.githubusercontent.com/53232322/124511889-211fb300-dda5-11eb-8bc4-bfc9d11373f7.jpg)

**Comment by jvanitallie** [comment]
I created pull request #115  to address the issue - I had a hard time getting it to build / test correctly in my environment though, so treat that as an "idea" PR - not a fully tested one

**Comment by tanhakabir** [comment]
Hm `+` should be working or it has worked on my side consistently
