### ISSUE TITLE
Cannot open resource with notebook editory type 'rest-book'

### ISSUE THREAD

**Issue by ssnyder** [tanhakabir/rest-book#116]
I cannot start editing any file (existing or blank) with the .restbook extension.  I get the error:

> Cannot open resource with notebook editory type 'rest-book',
> please check if you have the right extension installed or enabled

Further when I use the command palette to create a new RESTBook I get the following error:
> Command 'REST Book: Create a new blank REST Notebook' resulted in an error (command 'rest-book.newNotebook' not found)

This occurs with the 3.2.0 and the 3.1.0 versions on the current version of VSCode (1.58.2?? just updated it last night)

**Comment by tanhakabir** [comment]
Hmm! are you on VS Code stable? And was it working before on there?

**Comment by hansWurst-creator** [comment]
I have the same issue.  I am on stable and just installed the extension and wanted to try it out.

**Comment by ssnyder** [comment]
I am on stable.  I  don't think it ever worked.

**Comment by tanhakabir** [comment]
Sorry yes the extension for now is still on Insiders only. It will be on stable next month with the next release of VS Code!
