### ISSUE TITLE
Is it possible to use variable inside url?

### ISSUE THREAD

**Issue by imchkkim** [tanhakabir/rest-book#120]
I have several server instances in development environment. For example, one instance is http://localhost:3000 and the other is http://192.168.0.201:7899 and so on.
And I have many api request code in restbook. If I want to switch between servers, I had to change url parts one by one, which is not practical.
Is it possible to use variable inside url? I tried but it seems not working for now.

For example,
```
let api = http://192.168.0.201:7899
let api2 = http://localhost:3000
GET @api/users
GET @api2/users
```

**Comment by tanhakabir** [comment]
you can use variables with `$` in front.
