### ISSUE TITLE
create notebook from command palette

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/rest-book#67]

**Comment by sanket-bhalerao** [comment]
currently getting 
![image](https://user-images.githubusercontent.com/9264813/114144284-c8ba5000-9932-11eb-9471-7dab58d8fb9d.png)
when i try to create notebook from the command palette

**Comment by tanhakabir** [comment]
whoops thanks for letting me know! unfortunately at the moment to create a new notebook I would need to add a keybinding instead.

**Comment by tanhakabir** [comment]
New api point was introduced to make this feature easy
