### ISSUE TITLE
add syntax highlighting for returned data

### ISSUE THREAD

**Issue by tanhakabir** [tanhakabir/rest-book#73]

**Comment by Kappyh** [comment]
Hi, this project is open to contribute? :smiley:

**Comment by tanhakabir** [comment]
@Kappyh Hey! Yes of course!

**Comment by Kappyh** [comment]
Nice, I wanna help in this feature, you have some idea  in mind how you wanna this highlighting in the response?

**Comment by tanhakabir** [comment]
Hm no I haven't had a chance to explore what I want to do yet. I'd probably start by exploring what api's and things are possible in webviews. There's the vscode theme colors that are usable in webviews.

If you want to just contribute, you could take a look at the other issues if you think any of those would be easier to start with!

**Comment by RandomFractals** [comment]
shikijs would be the easiest to use. see this simple example notebook: https://observablehq.com/@randomfractals/hello-shiki-highlighter

docs view ext. has the setup you can just copy for your output renderer: https://github.com/mattbierner/vscode-docs-view/blob/master/src/codeHighlighter.ts

**Comment by tanhakabir** [comment]
Thanks @RandomFractals!

**Comment by RandomFractals** [comment]
@tanhakabir you might want to consider adding expand/collapse view for xmla and json data and simple data grid for csv results. I think those are the most common use cases for the data responses, and I am not sure simply adding code highlighting would be enough to make viewing that data a pleasant or useful experience.

**Comment by RandomFractals** [comment]
maybe we should create a separate ticket for what's called JSONView in browser debug tools ecosystem. I can see a bunch of other response viewers that would need to be added here, like png/svg viewer for image requests, etc.

**Comment by tanhakabir** [comment]
@RandomFractals good idea! With the current api you can actually register one renderer to many mime types like so:

```json
"notebookOutputRenderer": [
      {
        "id": "rest-book",
        "displayName": "REST Book Renderer",
        "entrypoint": "./dist/renderer.js",
        "mimeTypes": [
          "x-application/rest-book"
          <MORE TYPES HERE>
        ]
      }
    ]
```

so we could do somethings like 
```json
 "x-application/rest-book-json",
 "x-application/rest-book-html",
etc...
```

and then pivot on the view for the data tab based on mimetype. The yo generator for notebooks shows pulling out the mime type in the renderer: [client/index.ts line 52](https://github.com/microsoft/vscode-generator-code/blob/24c0f41b64159582078d2bbacaa4ae8aa8c090e4/generators/app/templates/ext-notebook-renderer/src/client/index.ts#L52)

So I believe the mime type text should be available under `event` object.

Creating the different views might be a hefty amount of work and so I might be putting this off until May.

**Comment by RandomFractals** [comment]
awesome! I think we should split this ticket into multiple for JSONView, XMLView, ImageView, and GeoData, and DataView I'd like to add for geo data formats and flat data files like csv, etc.

I can probably help you out in May too.

**Comment by RandomFractals** [comment]
You can close this ticket if you'd like. I created separate issues for the corresponding rich output viewers. I think it would be easier to tackle them separately.

**Comment by tanhakabir** [comment]
Good call!
