### ISSUE TITLE
add secrets to request headers

### ISSUE THREAD

**Issue by RandomFractals** [tanhakabir/rest-book#78]
some REST APIs typically use app or api key headers to validate requests.

Would be great to pass those required custom header values from vscode secrets, without adding them as plain text in rest books.

see how to use new Secrets API here: https://github.com/microsoft/vscode/issues/112249#issuecomment-754426797

**Comment by tanhakabir** [comment]
oh good point! Thanks for pointing me to the API 😊  I'll into this, this week!

**Comment by RandomFractals** [comment]
great! simple example would be something along the lines of XYZ requires XYZ-API-KEY header

```
XYZ-API-KEY: <Key>
```

not sure how you'd want to demarcate this encrypted key in the header line of your notebook cell. 

also, extensions can set those keys too, but maybe your output renderer can have a Secrets tab that allows us to set and reveal those keys used for HTTPS requests.

**Comment by tanhakabir** [comment]
@RandomFractals hey! added secrets and editing abilities with quick picks

![recording (33)](https://user-images.githubusercontent.com/12758612/115969402-9fccba00-a4f1-11eb-8252-c1ef0cf98c0b.gif)

**Comment by tanhakabir** [comment]
Renamed secrets to be accessible through $SECRETS

**Comment by RandomFractals** [comment]
@tanhakabir this looks good! with this chance, can we also access added secrets when constructing GET urls with query params? Some platforms require app/api keys to be passed that way for their data/service calls.

I'll check it out today. Thanks for this update!

**Comment by tanhakabir** [comment]
@RandomFractals yep! It's available now! I made the secrets available like variables so you can use them in query params, headers, and bodies 😊

**Comment by RandomFractals** [comment]
worked like magic. I can't share my actual call screen pic, but here is an anonimized bit I just used for on of my rest endpoint tests:

```
https://api.<XYZ>.com/api/<serviceName>
    ?from=1475085940
    &to=1619085940
XYZ-API-KEY: $SECRETS.XYZ-API-KEY
XYZ-APPLICATION-KEY: $SECRETS.XYZ-APPLICATION-KEY
Content-Type: application/json
```
🙌

**Comment by dfinke** [comment]
I'm trying to authenticate to GitHub with my PAT.

Do I have the right syntax for the `Authorization`? 

![image](https://user-images.githubusercontent.com/67258/118506062-fc8b5100-b6fa-11eb-8421-d495af8a6005.png)

**Comment by tanhakabir** [comment]
Hm let me see there might be a bug for this case! Will have a fix out in the next 1-2 hours

**Comment by RandomFractals** [comment]
that would be nice. does that mean with that fix we can mock JWT for oauth too via $SECRETS vars? 🤔

**Comment by RandomFractals** [comment]
btw, good way to test OAuth would be using unfolded.ai data sdk that has the whole process nicely documented:

https://docs.unfolded.ai/data-sdk/authentication

**Comment by tanhakabir** [comment]
I didn't look into more complexity with OAuth but fixed the issue @dfinke had

**Comment by RandomFractals** [comment]
that's fine. I should have added those comments on getting oauth tokens to work in #24.

**Comment by dfinke** [comment]
Thank you, works.
