### ISSUE TITLE
Unable to Open file with rest-book

### ISSUE THREAD

**Issue by alfonzjanfrithz** [tanhakabir/rest-book#79]
After I installed the extension, and about to test, here is what i got when opening .restbook

![image](https://user-images.githubusercontent.com/3738789/115496967-5ab04a00-a29d-11eb-800b-1014e1831ee7.png)

Here is what i got from the console log when i toggle the developer tools in vscode
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1904 Activating extension 'tanhakabir.rest-book' failed: vscode__WEBPACK_IMPORTED_MODULE_1__.notebook.createNotebookController is not a function.
_logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1904
```

Another error is as follows:
```
notificationsAlerts.ts:40 Cannot open resource with notebook editor type 'rest-book', please check if you have the right extension installed or enabled.
```

**Comment by tanhakabir** [comment]
Are you on the latest version of Insiders? Version: 1.56.0-insider (Universal)

The extension will break in any older versions of Insiders since the Notebook APIs change between every version at the moment.

**Comment by alfonzjanfrithz** [comment]
Ah that's probably why, I am not currently in insider version. I am gonna have a try again with the insider version.

Thank you for your prompt response!

```
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393
```
