### ISSUE TITLE
add WebView response output renderer

### ISSUE THREAD

**Issue by RandomFractals** [tanhakabir/rest-book#90]
for rendering actual web pages, in addition to XMLView to display html response in xml tree (#86)

**Comment by RandomFractals** [comment]
we can probably just use iframe for this and set it to GET url for the page to get started.

**Comment by tanhakabir** [comment]
By webview, do you mean by a rendered view of the html received? if this is the case there is actually already an output for rendered html

**Comment by RandomFractals** [comment]
@tanhakabir oh, somehow I missed that part in docs and have not tried to just load a simple google.com page. will give it a go. Thanks!

**Comment by RandomFractals** [comment]
nope. I get raw html that is not even formatted:

![image](https://user-images.githubusercontent.com/656833/116487464-a347a480-a855-11eb-89ea-84bac17a1f19.png)

**Comment by RandomFractals** [comment]
also, looks like styles on nb cell and nb view page are not cleared and overiden by the loaded page: 

![image](https://user-images.githubusercontent.com/656833/116488056-1271c880-a857-11eb-918c-1736362c010b.png)

Expected white google page render background in that cell output and retaining dark plus theme for the nb view ;)

**Comment by RandomFractals** [comment]
also, note that google branding logo image did not load in that built-in html mime type output renderer :(

**Comment by tanhakabir** [comment]
> probably need to update docs for this part

👍

**Comment by tanhakabir** [comment]
> also, looks like styles on nb cell and nb view page are not cleared and overidden by the loaded page

This looks like a bug and not intentional! Creating an issue for that now
