### ISSUE TITLE
Can CustomRenderer be a individual npm project?

### ISSUE THREAD

**Issue by cedric05** [tanhakabir/rest-book#92]
Hi, I know this is not the correct place to ask questions. 

I'm working on similar concept of rest-book, [dothttp](https://marketplace.visualstudio.com/items?itemName=ShivaPrasanth.dothttp-code). because of unavailability of documentation. I copied few parts of code from this repository.

I'm looking if [custom-renderer](https://github.com/tanhakabir/rest-book/tree/main/src/custom-renderer) can be a npm package for me. 
it would really help my project. (if otherwise, can you please give me pointers]

Thanks.

**Comment by tanhakabir** [comment]
Hey! So not directly an npm package but if you're able to set up a script that bundles your package into one JS file then you can set that to be the entry-point like so: https://github.com/tanhakabir/rest-book/blob/820fb1cbf6419c416319fda986b9faa7f2f4de4b/package.json#L36

In the future it would great if you could post issues like this to the https://github.com/microsoft/vscode so others who are working with notebooks can see your questions about the API.
