### ISSUE TITLE
add more test REST notebooks and examples

### ISSUE THREAD

**Issue by RandomFractals** [tanhakabir/rest-book#93]
I suggest we create a standard `./notebooks` folder and add them there.

We can exclude them from packaging of this extension if you'd like in `.vscodeignore`:

```
...
notebooks/**
...
```

**Comment by RandomFractals** [comment]
@tanhakabir I would like to use those two notebooks for html, image and json results testing to see what we need to do to add image view (#87) and better json data display.

**Comment by tanhakabir** [comment]
cool thank you for your help!
